import { StyleSheet } from 'react-native';

export const getHomeStyles = (mediaType, mode, theme) => {
  const colors = theme[mediaType][mode];

  return StyleSheet.create({
    homeContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    section: {
      marginVertical: 16,
      paddingHorizontal: 16,
    },
    sectionWithBorder: {
      borderWidth: 2,
      borderColor: colors.primary,
      borderRadius: 12,
      marginHorizontal: 16,
      marginVertical: 8,
      padding: 16,
      backgroundColor: mode === 'dark' ? 'rgba(75, 0, 130, 0.1)' : 'rgba(240, 240, 240, 0.5)',
    },
    movieCardBorder: {
      borderWidth: 2,
      borderColor: colors.primary,
      borderRadius: 12,
      marginHorizontal: 4,
      marginVertical: 4,
      padding: 3,
      backgroundColor: mode === 'dark' ? 'rgba(75, 0, 130, 0.1)' : 'rgba(240, 240, 240, 0.5)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
    },
    toggleBorder: {
      borderWidth: 2,
      borderColor: colors.primary,
      borderRadius: 27,
      padding: 2,
      marginHorizontal: 16,
      alignSelf: 'center',
      backgroundColor: 'transparent',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 12,
      color: colors.text,
      fontFamily: colors.font.header,
    },
    genreItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 12,
      borderRadius: 8,
      marginVertical: 4,
      backgroundColor: colors.card,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    genreName: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      fontFamily: colors.font.body,
    },
    genreScore: {
      fontSize: 16,
      color: colors.text,
      fontFamily: colors.font.body,
    },
    carouselContainer: {
      marginVertical: 12,
      height: 280,
    },
    carouselContent: {
      paddingLeft: 16,
    },
    carouselItem: {
      marginRight: 16,
      borderRadius: 12,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 1, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 5,
    },
    ratingButtonContainer: {
      position: 'absolute',
      bottom: 8,
      right: 8,
      borderRadius: 20,
      padding: 6,
      zIndex: 5,
      backgroundColor: colors.primary,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    quickRateButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    rateButtonText: {
      fontSize: 12,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    diagonalContainer: {
      overflow: 'hidden',
      height: 320,
      marginVertical: 10,
    },
    swipeInstructions: {
      textAlign: 'center',
      fontSize: 12,
      fontStyle: 'italic',
      marginTop: 8,
      marginBottom: 16,
      color: colors.text,
    },
    enhancedCard: {
      borderRadius: 12,
      overflow: 'hidden', 
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 3 },
      shadowOpacity: 0.25,
      shadowRadius: 5,
      elevation: 6,
    },
    movieInfoBox: {
      padding: 8,
      borderBottomLeftRadius: 12,
      borderBottomRightRadius: 12,
      backgroundColor: colors.card,
    },
    movieYear: {
      fontSize: 12,
      marginTop: 2,
      color: colors.text,
    },
    genreTag: {
      fontSize: 11,
      marginTop: 2,
      fontStyle: 'italic',
      color: colors.text,
    },
  });
};