import { StyleSheet, Platform, Dimensions } from 'react-native';

const { height, width } = Dimensions.get('window');

// Function to get themed modal styles
const getModalStyles = (mediaType = 'movie', mode = 'light', theme) => {
  const colors = theme[mediaType][mode];

  return StyleSheet.create({
    // Existing modal styles (keeping your current structure)
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    modalContent: {
      width: '100%',
      padding: 20,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      backgroundColor: colors.card,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 8,
      paddingBottom: Platform.OS === 'ios' ? 30 : 20,
      maxHeight: height * 0.8,
    },
    animatedContainer: {
      width: '100%',
      position: 'relative',
      alignSelf: 'center',
    },
    modalHandle: {
      width: 40,
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.subText,
      alignSelf: 'center',
      marginBottom: 15,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
      color: colors.text,
      fontFamily: colors.font.header,
    },
    formContainer: {
      marginVertical: 10,
    },
    inputField: {
      width: '100%',
      borderWidth: 1,
      borderColor: colors.secondary,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      marginVertical: 8,
      textAlign: 'center',
      backgroundColor: colors.background,
      color: colors.text,
      fontFamily: colors.font.body,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 20,
    },
    modalButton: {
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 10,
      flex: 1,
      marginHorizontal: 8,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
    },
    primaryButton: {
      backgroundColor: colors.primary,
    },
    cancelButton: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: colors.text,
      elevation: 0,
      shadowOpacity: 0,
    },
    modalButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      fontFamily: colors.font.body,
    },
    keyboardAvoiding: {
      flex: 1,
      width: '100%',
    },
    backdropPressArea: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    errorText: {
      color: '#FF3B30',
      fontSize: 14,
      marginTop: 5,
      textAlign: 'center',
      fontFamily: colors.font.body,
    },

    // Movie Detail Modal Styles
    detailModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.8)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    detailModalContent: {
      width: width * 0.85,
      maxWidth: 350,
      backgroundColor: colors.primary,
      borderRadius: 20,
      padding: 20,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 10,
      maxHeight: height * 0.9,
    },
    detailPoster: {
      width: 140,
      height: 210,
      borderRadius: 12,
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    detailTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 5,
      fontFamily: colors.font.header,
      lineHeight: 24,
    },
    detailYear: {
      fontSize: 16,
      color: colors.text,
      textAlign: 'center',
      marginBottom: 8,
      fontFamily: colors.font.body,
    },
    detailScore: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.accent,
      textAlign: 'center',
      marginBottom: 12,
      fontFamily: colors.font.body,
    },
    detailActors: {
      fontSize: 14,
      color: colors.text,
      textAlign: 'center',
      marginBottom: 12,
      paddingHorizontal: 10,
      fontFamily: colors.font.body,
      lineHeight: 18,
    },
    detailPlot: {
      fontSize: 14,
      color: colors.subText,
      textAlign: 'center',
      marginBottom: 20,
      paddingHorizontal: 5,
      lineHeight: 20,
      fontFamily: colors.font.body,
    },
    streamingRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
      minHeight: 40,
      paddingHorizontal: 10,
    },
    platformIcon: {
      width: 32,
      height: 32,
      marginHorizontal: 4,
      borderRadius: 6,
      backgroundColor: '#FFFFFF',
    },
    buttonRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      marginBottom: 20,
      paddingHorizontal: 5,
    },
    actionButton: {
      backgroundColor: colors.card,
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 10,
      flex: 1,
      marginHorizontal: 3,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 3,
    },
    actionButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
      fontFamily: colors.font.body,
      lineHeight: 16,
    },
    cancelButtonContainer: {
      paddingVertical: 8,
      paddingHorizontal: 20,
      alignItems: 'center',
    },
    cancelText: {
      color: colors.subText,
      fontSize: 16,
      fontFamily: colors.font.body,
      textDecorationLine: 'underline',
    },
    scrollContainer: {
      maxHeight: height * 0.7,
      width: '100%',
    },
    contentContainer: {
      alignItems: 'center',
      paddingBottom: 10,
    },
    watchlistButtonActive: {
      backgroundColor: colors.secondary,
    },
    watchlistButtonInactive: {
      backgroundColor: colors.card,
    },
  });
};

// Keep the original static styles for backward compatibility
const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalContent: {
    width: '100%',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 8,
    paddingBottom: Platform.OS === 'ios' ? 30 : 20,
    maxHeight: height * 0.8,
  },
  animatedContainer: {
    width: '100%',
    position: 'relative',
    alignSelf: 'center',
  },
  modalHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#CCCCCC',
    alignSelf: 'center',
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  formContainer: {
    marginVertical: 10,
  },
  inputField: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    marginVertical: 8,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  modalButton: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    flex: 1,
    marginHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  primaryButton: {
    // Colors set in component
  },
  cancelButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    elevation: 0,
    shadowOpacity: 0,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  keyboardAvoiding: {
    flex: 1,
    width: '100%',
  },
  backdropPressArea: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  errorText: {
    color: '#FF3B30',
    fontSize: 14,
    marginTop: 5,
    textAlign: 'center',
  },
});

export { getModalStyles };
export default modalStyles;